### ISSUE TITLE
SyntaxError in seq2seq_enhanced.py

### ISSUE THREAD

**Issue by nicolas-ivanov** [LeavesBreathe/Seq2Seq_Upgrade_TensorFlow#4]
Hello, Leaves! I'm trying to apply your the enchancements from you library, specifically I wanna use the upgraded rnn_cell and seq2seq:

```python
from seq2seq_upgrade import rnn_cell_enhanced as rnn_cell
from seq2seq_upgrade import seq2seq_enhanced as seq2seq
```
With the default tensorflow modules my code compiles and runs, however after substituting them with the lines above I get the following error:
```
Traceback (most recent call last):
  File "/home/nicolas/Code/tf_seq2seq_chatbot/bin/train.py", line 3, in <module>
    from tf_seq2seq_chatbot.lib.train import train
  File "/home/nicolas/Code/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/train.py", line 12, in <module>
    from tf_seq2seq_chatbot.lib.seq2seq_model_utils import create_model
  File "/home/nicolas/Code/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model_utils.py", line 11, in <module>
    from tf_seq2seq_chatbot.lib import seq2seq_model
  File "/home/nicolas/Code/tf_seq2seq_chatbot/tf_seq2seq_chatbot/lib/seq2seq_model.py", line 14, in <module>
    from seq2seq_upgrade import seq2seq_enhanced as seq2seq
  File "/usr/local/lib/python2.7/dist-packages/Seq2seq_upgrade-0.0.1-py2.7.egg/seq2seq_upgrade/seq2seq_enhanced.py", line 449
    squared_sum = tf.zeros(batch_size),tf.float32) #batch size in zeros
                                                 ^
SyntaxError: invalid syntax
```
Do you have any idea what can be the reason?

The complete code of my example is here: 
[https://github.com/nicolas-ivanov/tf_seq2seq_chatbot/tree/debug](https://github.com/nicolas-ivanov/tf_seq2seq_chatbot/tree/debug)

**Comment by LeavesBreathe** [comment]
This will be fixed in about an hour! I apologize for the mistake.
